language: go
go:
 - 1.6

install:
  - go get -t ./...
  - go get github.com/stretchr/testify/assert  # This doesn't pick up the testing dependency as they are tagged (int and end to end)

script:
 - go build ./cmd/repoclone/repoclone.go
 - go test -v -tags=integration           # Run integration tests